    LIST P=16F887
    #INCLUDE "P16F887.inc"
    __CONFIG _CONFIG1, _FOSC_INTRC_NOCLKOUT & _WDTE_OFF & _MCLRE_ON & _LVP_OFF
    ORG 0X00
    GOTO 0X05
    ORG 0X05

;CONTADORES PARA LOS DELAY DE 10mS
CONTADOR1_DEALY10mS EQU 0X20
CONDADOR2_DEALY10mS EQU 0X21

;CONTADORES PARA TENER REFERNECIA DE LAS UNIDADES Y DECENAS
CONTADORX10_UNIDAD EQU 0X22
CONTADORX10_DECENA EQU 0X23

;GUARDAN LA DIRECCION DE MEMORIA DE UNA POSICION ESPECIFICA (LA CUAL SERA CARGADA POR LA 
;SUBRUTINA, A PARTIR DE UNIDAD_TEMP Y DECENA_TEMP)DE LA TABLA PARA QUE LUEGO SEAN
;MOSTRADOS POR LA RUTINA PRINCIPAL
UNIDAD EQU 0X24
DECENA EQU 0X25
 
;UNIDA_TEMP Y DECENA_TEMP SON UTILIZADOS POR LA SUBRUTINA PARA IR CONTANDO
;LOS TIEMPO QUE PASAN DE LA RUTINA  
UNIDAD_TEMP EQU 0X26
DECENA_TEMP EQU 0X27

;TABLA DE NUMEROS
    MOVLW 0X3F;0
    MOVWF 0X70
    
    MOVLW 0X06;1
    MOVWF 0X71
    
    MOVLW 0X5B;2
    MOVWF 0X72
    
    MOVLW 0X4F;3
    MOVWF 0X73
    
    MOVLW 0X66;4
    MOVWF 0X74
    
    MOVLW 0X6D;5
    MOVWF 0X75
    
    MOVLW 0X7D;6
    MOVWF 0X76
    
    MOVLW 0X07;7
    MOVWF 0X77
    
    MOVLW 0X7F;8
    MOVWF 0X78
    
    MOVLW 0X67;9
    MOVWF 0x79
    
;CONFIGURACION DE PUERTOS E INTERRUPCIONES
    BANKSEL ANSEL
    CLRF ANSEL
    CLRF ANSELH
    BANKSEL TRISA
    MOVLW 0XFC
    MOVWF TRISA
    MOVLW 0X01
    MOVWF TRISB
    MOVLW 0X97
    MOVWF OPTION_REG
    BANKSEL INTCON
    MOVLW .98
    MOVWF TMR0
    MOVLW 0XB0
    MOVWF INTCON